[package]
name = "marble_machine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
anyhow = "1.0.66"
pretty_assertions = "1.3.0"
bevy = "0.9.0"
bevy-inspector-egui = "0.14.0"
bevy_pancam = {version = "0.7.0", features = ["bevy-inspector-egui", "bevy_egui"] }

once_cell = "1.16.0"
strum = "0.24"
strum_macros = "0.24"

[workspace]
resolver = "2"


